import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Animated3DBackground from "@/components/Animated3DBackground";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const circularStd = localFont({
	src: [
		{
			path: "../public/fonts/circular-std/CircularStd-Black.woff2",
			style: "normal",
			weight: "900",
		},
		{
			path: "../public/fonts/circular-std/CircularStd-BlackItalic.woff2",
			style: "italic",
			weight: "900",
		},
		{
			path: "../public/fonts/circular-std/CircularStd-Bold.woff2",
			style: "normal",
			weight: "bold",
		},
		{
			path: "../public/fonts/circular-std/CircularStd-BoldItalic.woff2",
			style: "italic",
			weight: "bold",
		},
		{
			path: "../public/fonts/circular-std/CircularStd-Book.woff2",
			style: "normal",
			weight: "normal",
		},
		{
			path: "../public/fonts/circular-std/CircularStd-BookItalic.woff2",
			style: "italic",
			weight: "normal",
		},
		{
			path: "../public/fonts/circular-std/CircularStd-Medium.woff2",
			style: "normal",
			weight: "500",
		},
		{
			path: "../public/fonts/circular-std/CircularStd-MediumItalic.woff2",
			style: "italic",
			weight: "500",
		},
	],
	display: "swap",
	variable: "--font-circular",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${circularStd.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Animated3DBackground />
				<main
					className="font-sans"
					style={{ position: "relative", zIndex: 2 }}
				>
					{children}
				</main>
			</body>
		</html>
	);
}
